### PR TITLE
Add datetimepicker for the starts_at field of /admin/events/new

### PR DESCRIPTION
**Pull request by xuebinglee**
[just_datetime_picker](https://github.com/mspanc/just-datetime-picker) is used to create a datetimepicker for the starts_at field of /admin/events/new, which oddly has already been installed but never been used.

### CODE REVIEW

**Comment by xuebinglee** [comment]
CI build fails because env var SECRET_KEY_BASE is missing. This seems to be the cause of all failed PR builds. 

Is it possible for someone to fix the Travis config? @jaylynch maybe?

**Comment by jaylynch** [comment]
It needs a basic .env configured for payment support and the like, I'll get a sample added to the documentation

**Comment by xuebinglee** [comment]
@jaylynch thanks for the prompt reply.
I notice that .env file appears in .gitignore. How about adding a .env.test file to make Travis happy?

**Comment by jaylynch** [comment]
That's the plan. :)

**Comment by xuebinglee** [comment]
@jaylynch I made a copy of sample.env, named it .env.test, and Travis become happy!

**Comment by xuebinglee** [comment]
@jaylynch I've kept my fork up to date with upstream's master.

**Comment by xuebinglee** [comment]
@jaylynch Hey Jay, any update on this pull request?

**Comment by jaylynch** [comment]
@xuebinglee Apologies! Had not noticed your update come through until your message. All looks good from here, merging.

**Pull request merged**
